import { Resend } from 'resend'
import { serverSupabaseServiceRole, serverSupabaseUser } from '#supabase/server'
import { z } from 'zod'

const schema = z.object({
  circleId: z.uuid(),
  email: z.email(),
})

export default defineEventHandler(async (event) => {
  console.log('[invite] received POST /api/circles/invite')
  const supabase = serverSupabaseServiceRole(event)
  const user = await serverSupabaseUser(event)

  if (!user?.sub) {
    console.warn('[invite] 401 — no authenticated user')
    throw createError({ statusCode: 401 })
  }

  const result = schema.safeParse(await readBody(event))
  if (!result.success) {
    console.warn(
      `[invite] 400 — zod rejected body (user ${user.sub}):`,
      result.error.issues,
    )
    throw createError({ statusCode: 400, message: 'Invalid request' })
  }
  const { circleId, email } = result.data
  console.log(`[invite] user ${user.sub} → ${email} (circle ${circleId})`)

  // Verify sender is owner or admin
  const { data: membership } = await supabase
    .from('circlemember')
    .select('role')
    .eq('user_id', user.sub)
    .eq('circle_id', circleId)
    .single()

  if (!membership || !['owner', 'admin'].includes(membership.role)) {
    console.warn(
      `[invite] 403 — user ${user.sub} has role ${membership?.role ?? 'none'} on circle ${circleId}`,
    )
    throw createError({
      statusCode: 403,
      message: 'Only owners and admins can invite',
    })
  }

  // Reject if the email already belongs to a current circle member. Scoped to
  // THIS circle so the check doesn't leak whether the email has an account in
  // some other circle (privacy). Uses an !inner join so the row only comes
  // back when both the circlemember row and the matching email exist.
  const { data: existingMember } = await (supabase as any)
    .from('circlemember')
    .select('user_id, user:user_id!inner(email)')
    .eq('circle_id', circleId)
    .eq('user.email', email)
    .maybeSingle()

  if (existingMember) {
    console.warn(
      `[invite] 409 — ${email} is already a member of circle ${circleId}`,
    )
    throw createError({
      statusCode: 409,
      message: 'already_member',
    })
  }

  // Check max pending invites (10 per circle)
  const { count } = await supabase
    .from('circleinvite')
    .select('*', { count: 'exact', head: true })
    .eq('circle_id', circleId)
    .eq('status', 'pending')

  if ((count ?? 0) >= 10) {
    console.warn(`[invite] 429 — circle ${circleId} already has ${count} pending invites`)
    throw createError({
      statusCode: 429,
      message: 'Max 10 pending invites per circle',
    })
  }

  // Expire any existing pending invites for this email before issuing a fresh one.
  // This lets owners resend at any time — the old link is invalidated, a new 7-day
  // window starts, and the 10-invite cap counts only truly-pending rows.
  await supabase
    .from('circleinvite')
    .update({ status: 'expired' })
    .eq('circle_id', circleId)
    .eq('email', email)
    .eq('status', 'pending')

  // Create invite record (token + expires_at generated by DB default)
  const { data: invite, error: inviteError } = await supabase
    .from('circleinvite')
    .insert({ circle_id: circleId, email })
    .select()
    .single()

  if (inviteError || !invite) {
    console.error(
      `[invite] 500 — circleinvite insert failed (circle ${circleId}, ${email}):`,
      inviteError,
    )
    throw createError({ statusCode: 500, message: 'Failed to create invite' })
  }
  console.log(`[invite] db row created (token ${invite.token.slice(0, 8)}…)`)

  // Fetch circle name + sender name for email
  const [{ data: circle }, { data: sender }] = await Promise.all([
    supabase.from('circle').select('name').eq('id', circleId).single(),
    (supabase as any)
      .from('user')
      .select('first_name, last_name, locale')
      .eq('id', user.sub)
      .single(),
  ])

  const senderName =
    [sender?.first_name, sender?.last_name].filter(Boolean).join(' ') ||
    'Someone'

  const config = useRuntimeConfig()

  if (config.resendApiKey) {
    const resend = new Resend(config.resendApiKey)
    const inviteUrl = `${config.appUrl}/invite/${invite.token}`
    const safeCircleName = circle?.name ?? 'a circle'
    const safeLocale = sender?.locale ?? 'en'
    try {
      const { data, error } = await resend.emails.send({
        from: 'Our Story <hello@ourstory.tinybit.app>',
        // A real reply-to (vs. unmonitored 'noreply@…') is a deliverability
        // signal — many spam filters dock points when replies bounce.
        replyTo: 'hello@ourstory.tinybit.app',
        to: email,
        subject: `${senderName} invited you to ${safeCircleName} on Our Story`,
        // Plain-text alternative bundled with HTML (multipart/alternative).
        // Gmail in particular rewards this over HTML-only emails.
        text: buildInviteEmailText({
          senderName,
          circleName: safeCircleName,
          inviteUrl,
          locale: safeLocale,
        }),
        html: buildInviteEmail({
          senderName,
          circleName: safeCircleName,
          inviteUrl,
          locale: safeLocale,
        }),
        // Gmail's bulk-sender requirements (Feb 2024) prefer this header
        // even on transactional sends. Provides a mailto-only fallback —
        // when there's a real unsubscribe endpoint, add the https variant.
        headers: {
          'List-Unsubscribe':
            '<mailto:hello@ourstory.tinybit.app?subject=unsubscribe>',
          'List-Unsubscribe-Post': 'List-Unsubscribe=One-Click',
        },
      })
      if (error) {
        console.error(
          `[invite] Resend rejected send to ${email} (circle ${circleId}):`,
          error,
        )
      } else {
        console.log(
          `[invite] sent to ${email} (id: ${data?.id}, circle ${circleId})`,
        )
      }
    } catch (err) {
      console.error(
        `[invite] threw while sending to ${email} (circle ${circleId}):`,
        err,
      )
    }
  } else {
    console.log(
      `[invite] RESEND_API_KEY missing; invite link for ${email}: ${config.appUrl}/invite/${invite.token}`,
    )
  }

  return { ok: true }
})

function buildInviteEmail({
  senderName,
  circleName,
  inviteUrl,
  locale,
}: {
  senderName: string
  circleName: string
  inviteUrl: string
  locale: string
}) {
  if (locale === 'zh-CN') {
    return `
      <div style="font-family: Georgia, serif; max-width: 480px; margin: 0 auto; padding: 40px 24px; background: #fffdf8; color: #1a1a1a;">
        <p style="font-size: 11px; font-weight: bold; letter-spacing: 0.12em; text-transform: uppercase; color: #888; margin: 0 0 28px;">Our Story</p>
        <h2 style="font-size: 22px; font-weight: bold; margin: 0 0 12px; line-height: 1.3;">${senderName} 邀请你加入他们的故事</h2>
        <p style="color: #555; margin: 0 0 32px; line-height: 1.6; font-size: 15px;">
          ${senderName} 在 Our Story 上创建了 <strong>${circleName}</strong> — 一个私密的空间，用来分享记忆、里程碑和珍贵时刻。
        </p>
        <a href="${inviteUrl}" style="display: block; background: #1a1a1a; color: #fff; text-align: center; padding: 16px 24px; border-radius: 10px; text-decoration: none; font-size: 15px; font-weight: 600;">
          加入 ${circleName} →
        </a>
        <p style="color: #999; font-size: 12px; margin-top: 32px; text-align: center; line-height: 1.6;">
          无需账号即可浏览。加入后可添加你自己的记忆。<br/>
          私密、仅限邀请 · 无广告
        </p>
      </div>
    `
  }

  return `
    <div style="font-family: Georgia, serif; max-width: 480px; margin: 0 auto; padding: 40px 24px; background: #fffdf8; color: #1a1a1a;">
      <p style="font-size: 11px; font-weight: bold; letter-spacing: 0.12em; text-transform: uppercase; color: #888; margin: 0 0 28px;">Our Story</p>
      <h2 style="font-size: 22px; font-weight: bold; margin: 0 0 12px; line-height: 1.3;">${senderName} started your story</h2>
      <p style="color: #555; margin: 0 0 32px; line-height: 1.6; font-size: 15px;">
        ${senderName} has created <strong>${circleName}</strong> on Our Story — a private space to share memories, milestones, and moments together.
      </p>
      <a href="${inviteUrl}" style="display: block; background: #1a1a1a; color: #fff; text-align: center; padding: 16px 24px; border-radius: 10px; text-decoration: none; font-size: 15px; font-weight: 600;">
        Join ${circleName} →
      </a>
      <p style="color: #999; font-size: 12px; margin-top: 32px; text-align: center; line-height: 1.6;">
        No account needed to look. Join to add your own memories.<br/>
        Private, invite-only · No ads
      </p>
    </div>
  `
}

// Plain-text alternative bundled into the multipart/alternative email.
// Most users never see this — but spam filters (especially Gmail) actively
// reward emails that include both parts, and rendering the same content
// in plain text helps screen readers and minimal clients.
function buildInviteEmailText({
  senderName,
  circleName,
  inviteUrl,
  locale,
}: {
  senderName: string
  circleName: string
  inviteUrl: string
  locale: string
}) {
  if (locale === 'zh-CN') {
    return [
      `${senderName} 邀请你加入 ${circleName}`,
      '',
      `${senderName} 在 Our Story 上创建了 ${circleName} — 一个私密的空间，用来分享记忆、里程碑和珍贵时刻。`,
      '',
      `加入 ${circleName}: ${inviteUrl}`,
      '',
      '无需账号即可浏览。加入后可添加你自己的记忆。',
      '私密、仅限邀请 · 无广告',
    ].join('\n')
  }

  return [
    `${senderName} invited you to ${circleName} on Our Story.`,
    '',
    `${senderName} has created ${circleName} on Our Story — a private space to share memories, milestones, and moments together.`,
    '',
    `Join ${circleName}: ${inviteUrl}`,
    '',
    'No account needed to look. Join to add your own memories.',
    'Private, invite-only · No ads.',
  ].join('\n')
}
