import { Resend } from "resend"
import { serverSupabaseServiceRole, serverSupabaseUser } from "#supabase/server"
import { z } from "zod"

const schema = z.object({
  circleId: z.uuid(),
  email: z.email(),
})

export default defineEventHandler(async (event) => {
  const supabase = serverSupabaseServiceRole(event)
  const user = await serverSupabaseUser(event)

  if (!user?.sub) throw createError({ statusCode: 401 })

  const result = schema.safeParse(await readBody(event))
  if (!result.success) throw createError({ statusCode: 400, message: "Invalid request" })
  const { circleId, email } = result.data

  // Verify sender is owner or admin
  const { data: membership } = await supabase
    .from("circlemember")
    .select("role")
    .eq("user_id", user.sub)
    .eq("circle_id", circleId)
    .single()

  if (!membership || !["owner", "admin"].includes(membership.role)) {
    throw createError({ statusCode: 403, message: "Only owners and admins can invite" })
  }

  // Check max pending invites (10 per circle)
  const { count } = await supabase
    .from("circleinvite")
    .select("*", { count: "exact", head: true })
    .eq("circle_id", circleId)
    .eq("status", "pending")

  if ((count ?? 0) >= 10) {
    throw createError({ statusCode: 429, message: "Max 10 pending invites per circle" })
  }

  // Expire any existing pending invites for this email before issuing a fresh one.
  // This lets owners resend at any time — the old link is invalidated, a new 7-day
  // window starts, and the 10-invite cap counts only truly-pending rows.
  await supabase
    .from("circleinvite")
    .update({ status: "expired" })
    .eq("circle_id", circleId)
    .eq("email", email)
    .eq("status", "pending")

  // Create invite record (token + expires_at generated by DB default)
  const { data: invite, error: inviteError } = await supabase
    .from("circleinvite")
    .insert({ circle_id: circleId, email })
    .select()
    .single()

  if (inviteError || !invite) {
    throw createError({ statusCode: 500, message: "Failed to create invite" })
  }

  // Fetch circle name + sender name for email
  const [{ data: circle }, { data: sender }] = await Promise.all([
    supabase.from("circle").select("name").eq("id", circleId).single(),
    (supabase as any).from("user").select("first_name, last_name, locale").eq("id", user.sub).single(),
  ])

  const senderName = [sender?.first_name, sender?.last_name].filter(Boolean).join(" ") || "Someone"

  const config = useRuntimeConfig()

  if (config.resendApiKey) {
    const resend = new Resend(config.resendApiKey)
    await resend.emails.send({
      from: "Our Story <hello@our-story.tinybit.app>",
      to: email,
      subject: `${senderName} invited you to ${circle?.name ?? "a circle"} on Our Story`,
      html: buildInviteEmail({
        senderName,
        circleName: circle?.name ?? "a circle",
        inviteUrl: `${config.appUrl}/invite/${invite.token}`,
        locale: sender?.locale ?? "en",
      }),
    })
  } else {
    console.log(`[dev] invite link for ${email}: ${config.appUrl}/invite/${invite.token}`)
  }

  return { ok: true }
})

function buildInviteEmail({ senderName, circleName, inviteUrl, locale }: {
  senderName: string
  circleName: string
  inviteUrl: string
  locale: string
}) {
  if (locale === "zh-CN") {
    return `
      <div style="font-family: Georgia, serif; max-width: 480px; margin: 0 auto; padding: 40px 24px; background: #fffdf8; color: #1a1a1a;">
        <p style="font-size: 11px; font-weight: bold; letter-spacing: 0.12em; text-transform: uppercase; color: #888; margin: 0 0 28px;">Our Story</p>
        <h2 style="font-size: 22px; font-weight: bold; margin: 0 0 12px; line-height: 1.3;">${senderName} 邀请你加入他们的故事</h2>
        <p style="color: #555; margin: 0 0 32px; line-height: 1.6; font-size: 15px;">
          ${senderName} 在 Our Story 上创建了 <strong>${circleName}</strong> — 一个私密的空间，用来分享记忆、里程碑和珍贵时刻。
        </p>
        <a href="${inviteUrl}" style="display: block; background: #1a1a1a; color: #fff; text-align: center; padding: 16px 24px; border-radius: 10px; text-decoration: none; font-size: 15px; font-weight: 600;">
          加入 ${circleName} →
        </a>
        <p style="color: #999; font-size: 12px; margin-top: 32px; text-align: center; line-height: 1.6;">
          无需账号即可浏览。加入后可添加你自己的记忆。<br/>
          私密、仅限邀请 · 无广告
        </p>
      </div>
    `
  }

  return `
    <div style="font-family: Georgia, serif; max-width: 480px; margin: 0 auto; padding: 40px 24px; background: #fffdf8; color: #1a1a1a;">
      <p style="font-size: 11px; font-weight: bold; letter-spacing: 0.12em; text-transform: uppercase; color: #888; margin: 0 0 28px;">Our Story</p>
      <h2 style="font-size: 22px; font-weight: bold; margin: 0 0 12px; line-height: 1.3;">${senderName} started your story</h2>
      <p style="color: #555; margin: 0 0 32px; line-height: 1.6; font-size: 15px;">
        ${senderName} has created <strong>${circleName}</strong> on Our Story — a private space to share memories, milestones, and moments together.
      </p>
      <a href="${inviteUrl}" style="display: block; background: #1a1a1a; color: #fff; text-align: center; padding: 16px 24px; border-radius: 10px; text-decoration: none; font-size: 15px; font-weight: 600;">
        Join ${circleName} →
      </a>
      <p style="color: #999; font-size: 12px; margin-top: 32px; text-align: center; line-height: 1.6;">
        No account needed to look. Join to add your own memories.<br/>
        Private, invite-only · No ads
      </p>
    </div>
  `
}
