import { Resend } from "resend"
import { serverSupabaseServiceRole, serverSupabaseUser } from "#supabase/server"

export default defineEventHandler(async (event) => {
  const supabase = serverSupabaseServiceRole(event)
  const user = await serverSupabaseUser(event)
  const { familyId, email } = await readBody(event)

  if (!user?.sub) throw createError({ statusCode: 401 })
  if (!familyId || !email) throw createError({ statusCode: 400, message: "familyId and email are required" })

  // Verify sender is owner or admin
  const { data: membership } = await supabase
    .from("familymember")
    .select("role")
    .eq("user_id", user.sub)
    .eq("family_id", familyId)
    .single()

  if (!membership || !["owner", "admin"].includes(membership.role)) {
    throw createError({ statusCode: 403, message: "Only owners and admins can invite" })
  }

  // Check max pending invites (10 per family)
  const { count } = await supabase
    .from("familyinvite")
    .select("*", { count: "exact", head: true })
    .eq("family_id", familyId)
    .eq("status", "pending")

  if ((count ?? 0) >= 10) {
    throw createError({ statusCode: 429, message: "Max 10 pending invites per family" })
  }

  // Check for an existing pending invite for this email
  const { data: existing } = await supabase
    .from("familyinvite")
    .select("id")
    .eq("family_id", familyId)
    .eq("email", email)
    .eq("status", "pending")
    .maybeSingle()

  if (existing) {
    throw createError({ statusCode: 409, message: "An invite has already been sent to this email" })
  }

  // Create invite record (token + expires_at generated by DB default)
  const { data: invite, error: inviteError } = await supabase
    .from("familyinvite")
    .insert({ family_id: familyId, email })
    .select()
    .single()

  if (inviteError || !invite) {
    throw createError({ statusCode: 500, message: "Failed to create invite" })
  }

  // Fetch family name + sender name for email
  const [{ data: family }, { data: sender }] = await Promise.all([
    supabase.from("family").select("name").eq("id", familyId).single(),
    supabase.from("user").select("first_name, last_name").eq("id", user.sub).single(),
  ])

  const senderName = [sender?.first_name, sender?.last_name].filter(Boolean).join(" ") || "Someone"

  const config = useRuntimeConfig()

  if (config.resendApiKey) {
    const resend = new Resend(config.resendApiKey)
    await resend.emails.send({
      from: "Our Story <hello@our-story.tinybit.app>",
      to: email,
      subject: `${senderName} invited you to ${family?.name ?? "a circle"} on Our Story`,
      html: buildInviteEmail({
        senderName,
        circleName: family?.name ?? "a circle",
        inviteUrl: `${config.appUrl}/invite/${invite.token}`,
      }),
    })
  } else {
    console.log(`[dev] invite link for ${email}: ${config.appUrl}/invite/${invite.token}`)
  }

  return { ok: true }
})

function buildInviteEmail({ senderName, circleName, inviteUrl }: {
  senderName: string
  circleName: string
  inviteUrl: string
}) {
  return `
    <div style="font-family: Georgia, serif; max-width: 480px; margin: 0 auto; padding: 40px 24px; background: #fffdf8; color: #1a1a1a;">
      <p style="font-size: 11px; font-weight: bold; letter-spacing: 0.12em; text-transform: uppercase; color: #888; margin: 0 0 28px;">Our Story</p>
      <h2 style="font-size: 22px; font-weight: bold; margin: 0 0 12px; line-height: 1.3;">${senderName} started your story</h2>
      <p style="color: #555; margin: 0 0 32px; line-height: 1.6; font-size: 15px;">
        ${senderName} has created <strong>${circleName}</strong> on Our Story — a private space to share memories, milestones, and moments together.
      </p>
      <a href="${inviteUrl}" style="display: block; background: #1a1a1a; color: #fff; text-align: center; padding: 16px 24px; border-radius: 10px; text-decoration: none; font-size: 15px; font-weight: 600;">
        Join ${circleName} →
      </a>
      <p style="color: #999; font-size: 12px; margin-top: 32px; text-align: center; line-height: 1.6;">
        No account needed to look. Join to add your own memories.<br/>
        Private, invite-only · No ads
      </p>
    </div>
  `
}
